// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using my_another_mvc_web_app.Data;

#nullable disable

namespace my_another_mvc_web_app.Migrations.UserDb
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250224051024_initial_Users_data_seeding")]
    partial class initial_Users_data_seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("my_another_mvc_web_app.Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Username = "tejas",
                            PasswordHash = "1234"
                        },
                        new
                        {
                            Username = "rahul",
                            PasswordHash = "1234"
                        },
                        new
                        {
                            Username = "rohit",
                            PasswordHash = "1234"
                        },
                        new
                        {
                            Username = "raju",
                            PasswordHash = "1234"
                        },
                        new
                        {
                            Username = "ravi",
                            PasswordHash = "1234"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
